using System.Security.Cryptography;
using System.Text;

using Shimakaze.Sdk.Mix;

namespace Shimakaze.Sdk.Engine.Mix;

internal static class MixPacker
{
    public static async Task PackAsync(Stream output, IReadOnlyList<FileInfo> files, bool isTDMode = false, Encoding? fileNameEncoding = default, TextWriter? nameMapOutput = null, CancellationToken cancellationToken = default)
    {
        if (nameMapOutput is not null)
        {
            await nameMapOutput.WriteLineAsync("; Generated By Shimakaze.Sdk.Engine.Mix");
            await nameMapOutput.WriteLineAsync();
            await nameMapOutput.WriteLineAsync("[NameMap]");
        }

        MixTag? tag = MixTag.NONE;
        IdCalculator idCalculator = IdCalculators.TSIdCalculator;
        if (isTDMode)
        {
            tag = null;
            idCalculator = IdCalculators.TDIdCalculator;
        }

        int offset = 0;
        var entries = GC.AllocateUninitializedArray<MixEntry>(files.Count);
        for (int i = 0; i < files.Count; i++)
        {
            uint id = idCalculator(files[i].Name, fileNameEncoding);
            int size = (int)files[i].Length;
            entries[i] = new()
            {
                Id = id,
                Offset = offset,
                Size = size,
            };

            offset += size;

            if (nameMapOutput is not null)
                await nameMapOutput.WriteLineAsync($"0x{id:X8} = {files[i].Name}");
        }

        MixMetadata metadata = new((short)entries.Length, offset);
        var key = Span<byte>.Empty;
        if (tag.HasValue && tag.Value.HasFlag(MixTag.ENCRYPTED))
        {
            key = GC.AllocateUninitializedArray<byte>(56);
            RandomNumberGenerator.Fill(key);
        }

        Sdk.Mix.Mix.WriteMetadata(output, metadata, entries, tag, key);
        int bodyOffset = (int)output.Position;

        for (int i = 0; i < entries.Length; i++)
        {
            using var fs = files[i].OpenRead();
            await Sdk.Mix.Mix.WriteFileAsync(output, bodyOffset, entries[i], fs, cancellationToken: cancellationToken);
        }

        await output.FlushAsync(cancellationToken);
    }
}
