env:
  browser: true
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - plugin:vue/vue3-recommended
  - plugin:prettier/recommended
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
    - tsconfig.node.json
    - tsconfig.vscode.json
plugins:
  - vue
  - prettier
rules:
  {
    '@typescript-eslint/explicit-function-return-type': 'off',
    # 您猜怎么着？ 
    # 这个规则让我 await 了一个 vscode.window.showInformationMessage
    # 程序等死了
    '@typescript-eslint/no-floating-promises': 'off',
  }
