printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
bracketSameLine: true
arrowParens: avoid
endOfLine: auto
plugins:
  - prettier-plugin-pkg
  - prettier-plugin-organize-imports
