/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[\x20-\x7E]*$".
 */
export type CsfValueRoot = CsfSingleLineValue | CsfMultiLineValue | AdvancedCsfValue | CsfValueArray;
/**
 * CSF值结构
 */
export type CsfSingleLineValue = string;
/**
 * 多行CSF值结构
 */
export type CsfMultiLineValue = CsfSingleLineValue[];
/**
 * CSF额外值结构
 */
export type CsfExtraValue = string;

export interface CSFJsonV2Schema {
  protocol: number;
  version?: number;
  language?: number | ('en_US' | 'en_UK' | 'de' | 'fr' | 'es' | 'it' | 'jp' | 'Jabberwockie' | 'kr' | 'zh');
  /**
   * 文件主体
   */
  data: {
    [k: string]: CsfValueRoot;
  };
  [k: string]: unknown;
}
/**
 * 高级CSF值结构
 */
export interface AdvancedCsfValue {
  value: CsfSingleLineValue | CsfMultiLineValue;
  extra?: CsfExtraValue;
  [k: string]: unknown;
}
/**
 * CSF值数组结构
 */
export interface CsfValueArray {
  values: (CsfSingleLineValue | CsfMultiLineValue | AdvancedCsfValue)[];
  [k: string]: unknown;
}
