<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <!-- <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile> -->
    <!-- <RestoreLockedMode Condition="'$(ContinuousIntegrationBuild)' == 'true'">true</RestoreLockedMode> -->
    <!-- <NuGetLockFilePath>$(MSBuildThisFileDirectory)packages.lock.json</NuGetLockFilePath> -->
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="IDisposableAnalyzers" Version="4.0.8" />
  </ItemGroup>
  <ItemGroup Condition="$(ShimakazeSdkIsUnitTest)">
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="DotMake.CommandLine" Version="1.9.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="9.0.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="MSTest.TestAdapter" Version="3.8.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="3.8.0" />
    <PackageVersion Include="Sharprompt" Version="3.0.0" />
    <PackageVersion Include="ShellProgressBar" Version="5.2.0" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.6" />
    <PackageVersion Include="System.IO.Hashing" Version="9.0.2" />
    <PackageVersion Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
</Project>