<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="IDisposableAnalyzers" Version="4.0.8" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="DotMake.CommandLine" Version="3.6.0" />
    <PackageVersion Include="Microsoft.Build.Utilities.Core" Version="18.9.6" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
    <PackageVersion Include="StbImageSharp" Version="2.30.16" />
    <PackageVersion Include="StbImageWriteSharp" Version="1.16.7" />
    <PackageVersion Include="System.IO.Hashing" Version="10.0.11" />
    <PackageVersion Include="Vecc.YamlDotNet.Analyzers.StaticGenerator" Version="18.1.0" />
    <PackageVersion Include="XenoAtom.Terminal.UI" Version="3.9.0" />
    <PackageVersion Include="XenoAtom.Terminal.UI.Graphics" Version="3.9.0" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
  </ItemGroup>
</Project>