<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <GitVersionTargetFramework>net10.0</GitVersionTargetFramework>
    <UseProjectNamespaceForGitVersionInformation>true</UseProjectNamespaceForGitVersionInformation>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="IDisposableAnalyzers" Version="4.0.8" />
    <GlobalPackageReference Include="GitVersion.MsBuild" Version="6.7.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="DotMake.CommandLine" Version="3.1.0" />
    <PackageVersion Include="Draco.Lsp" Version="0.4.14-pre" />
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.7" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageVersion Include="Polyfill" Version="10.3.0" />
    <PackageVersion Include="Sharprompt" Version="3.0.1" />
    <PackageVersion Include="ShellProgressBar" Version="5.2.0" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageVersion Include="SkiaSharp" Version="3.119.2" />
    <PackageVersion Include="System.Collections.Immutable" Version="10.0.5" />
    <PackageVersion Include="System.IO.Hashing" Version="10.0.6" />
    <PackageVersion Include="System.Memory" Version="4.6.3" />
    <PackageVersion Include="System.Text.Json" Version="10.0.5" />
    <PackageVersion Include="YamlDotNet" Version="17.0.1" />
  </ItemGroup>
</Project>