<?xml version="1.0" encoding="UTF-8"?>
<Project>

  <ImportGroup>
    <Import Project="$(MSBuildThisFileDirectory)msbuild\Framework.props"/>
    <Import Project="$(MSBuildThisFileDirectory)msbuild\CSharp.props" Condition="$(ShimakazeSdkIsCSharp)"/>
    <Import Project="$(MSBuildThisFileDirectory)msbuild\UnitTests.props" Condition="$(ShimakazeSdkIsUnitTest)"/>
  </ImportGroup>

</Project>
