<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTrimmable>False</IsTrimmable>
    <IsAotCompatible>False</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
    <ProjectReference Include="..\Shimakaze.Sdk.Csf\Shimakaze.Sdk.Csf.csproj" />
  </ItemGroup>
</Project>
