<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <IsInherit>true</IsInherit>
    <NeutralLanguage>zh-Hans</NeutralLanguage>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="EastAsianWidth.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotMake.CommandLine" />
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\analyzers\Shimakaze.Sdk.UnicodeSourceGenerator\Shimakaze.Sdk.UnicodeSourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\ini\Shimakaze.Sdk.Inilyn\Shimakaze.Sdk.Inilyn.csproj" />
    <ProjectReference Include="..\..\ini\Shimakaze.Sdk.Inilyn.Analyzer\Shimakaze.Sdk.Inilyn.Analyzer.csproj" />
    <ProjectReference Include="..\Shimakaze.Sdk.Engine\Shimakaze.Sdk.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Resource.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resource.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Resource.*.resx" DependentUpon="Resources\Resource.resx" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Resource.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resource.resx</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
