<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <IsInherit>true</IsInherit>
    <PublishTrimmed>True</PublishTrimmed>
    <NeutralLanguage>zh-Hans</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotMake.CommandLine" />
    <PackageReference Include="Microsoft.CodeAnalysis.ResxSourceGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shimakaze.Sdk.Engine\Shimakaze.Sdk.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Resource.resx" />
    <EmbeddedResource Update="Resources\Resource.*.resx" DependentUpon="Resources\Resource.resx" />
  </ItemGroup>

</Project>
