//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shimakaze.Sdk.Engine.Cli.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shimakaze.Sdk.Engine.Cli.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Shimakaze.Sdk CSF 格式转换工具 的本地化字符串。
        /// </summary>
        internal static string Command_Csf_Description {
            get {
                return ResourceManager.GetString("Command.Csf.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将要被转换的字符串表文件 的本地化字符串。
        /// </summary>
        internal static string Command_Csf_Input_Description {
            get {
                return ResourceManager.GetString("Command.Csf.Input.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换前的字符串表文件格式 的本地化字符串。
        /// </summary>
        internal static string Command_Csf_InputFormat_Description {
            get {
                return ResourceManager.GetString("Command.Csf.InputFormat.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换后的字符串表文件保存路径 的本地化字符串。
        /// </summary>
        internal static string Command_Csf_Output_Description {
            get {
                return ResourceManager.GetString("Command.Csf.Output.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转换后的字符串表文件格式 的本地化字符串。
        /// </summary>
        internal static string Command_Csf_OutputFormat_Description {
            get {
                return ResourceManager.GetString("Command.Csf.OutputFormat.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shimakaze.Sdk 实用工具集 的本地化字符串。
        /// </summary>
        internal static string Command_Description {
            get {
                return ResourceManager.GetString("Command.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shimakaze.Sdk MIX 实用工具 的本地化字符串。
        /// </summary>
        internal static string Command_Mix_Description {
            get {
                return ResourceManager.GetString("Command.Mix.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shimakaze.Sdk MIX 内容释放工具 的本地化字符串。
        /// </summary>
        internal static string Command_Mix_Extract_Description {
            get {
                return ResourceManager.GetString("Command.Mix.Extract.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将要被释放的 MIX 文件 的本地化字符串。
        /// </summary>
        internal static string Command_Mix_Extract_Input_Description {
            get {
                return ResourceManager.GetString("Command.Mix.Extract.Input.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表示这是一个适用于 C&amp;C1 / RA1 的旧版无标记 MIX 文件 的本地化字符串。
        /// </summary>
        internal static string Command_Mix_Extract_IsTDMode_Description {
            get {
                return ResourceManager.GetString("Command.Mix.Extract.IsTDMode.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名对照表。
        ///将根据此对照表应用文件名，不填则写文件 ID 的本地化字符串。
        /// </summary>
        internal static string Command_Mix_Extract_NameMap_Description {
            get {
                return ResourceManager.GetString("Command.Mix.Extract.NameMap.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被释放的文件的存放位置 的本地化字符串。
        /// </summary>
        internal static string Command_Mix_Extract_Output_Description {
            get {
                return ResourceManager.GetString("Command.Mix.Extract.Output.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shimakaze.Sdk MIX 打包工具 的本地化字符串。
        /// </summary>
        internal static string Command_Mix_Pack_Description {
            get {
                return ResourceManager.GetString("Command.Mix.Pack.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名使用的字符编码 的本地化字符串。
        /// </summary>
        internal static string Command_Mix_Pack_Encoding_Description {
            get {
                return ResourceManager.GetString("Command.Mix.Pack.Encoding.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用河豚算法加密 MIX 文件 的本地化字符串。
        /// </summary>
        internal static string Command_Mix_Pack_Encrypt_Description {
            get {
                return ResourceManager.GetString("Command.Mix.Pack.Encrypt.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将要被打包的文件列表。 的本地化字符串。
        /// </summary>
        internal static string Command_Mix_Pack_Input_Description {
            get {
                return ResourceManager.GetString("Command.Mix.Pack.Input.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用旧的 MIX 格式。
        ///这将使用适用于 Red Alert 或 Tiberian Down 的游戏引擎的 ID 计算器和不写入 Mix Flag。 的本地化字符串。
        /// </summary>
        internal static string Command_Mix_Pack_IsTDMode_Description {
            get {
                return ResourceManager.GetString("Command.Mix.Pack.IsTDMode.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名对照表位置。留空则不生成文件名对照表。 的本地化字符串。
        /// </summary>
        internal static string Command_Mix_Pack_NameMapOutput_Description {
            get {
                return ResourceManager.GetString("Command.Mix.Pack.NameMapOutput.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成的MIX文件的路径。 的本地化字符串。
        /// </summary>
        internal static string Command_Mix_Pack_Output_Description {
            get {
                return ResourceManager.GetString("Command.Mix.Pack.Output.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shimakaze.Sdk SHP 生成工具 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Build_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Build.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将要使用的调色板颜色范围的结束索引 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Build_EndIndex_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Build.EndIndex.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象帧所属色蒙板图片列表 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Build_House_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Build.House.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象帧图片列表 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Build_Input_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Build.Input.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出的 SHP(TS) 文件 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Build_Output_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Build.Output.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将参考的调色板文件 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Build_Palette_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Build.Palette.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影子帧图片列表 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Build_Shadow_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Build.Shadow.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将要使用的调色板颜色范围的起始索引 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Build_StartIndex_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Build.StartIndex.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shimakaze.Sdk SHP 实用工具 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shimakaze.Sdk SHP 图片转换器 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Extract_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Extract.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束索引，为空则不批量转换 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Extract_EndIndex_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Extract.EndIndex.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片编码格式 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Extract_Format_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Extract.Format.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SHP的帧索引 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Extract_Index_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Extract.Index.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出的图片文件或输出文件夹路径 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Extract_Output_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Extract.Output.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将使用的调色板文件 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Extract_Palette_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Extract.Palette.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像质量 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Extract_Quality_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Extract.Quality.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渲染影子 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Extract_Shadow_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Extract.Shadow.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影子所使用的颜色 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Extract_ShadowColor_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Extract.ShadowColor.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SHP(TS) 文件 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Extract_Shp_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Extract.Shp.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用透明背景 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_Extract_Transparent_Description {
            get {
                return ResourceManager.GetString("Command.Shp.Extract.Transparent.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shimakaze.Sdk SHP 查看器 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_View_Description {
            get {
                return ResourceManager.GetString("Command.Shp.View.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将使用的调色板文件 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_View_Palette_Description {
            get {
                return ResourceManager.GetString("Command.Shp.View.Palette.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SHP(TS) 文件 的本地化字符串。
        /// </summary>
        internal static string Command_Shp_View_Shp_Description {
            get {
                return ResourceManager.GetString("Command.Shp.View.Shp.Description", resourceCulture);
            }
        }
    }
}
