<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Shimakaze.Sdk.Engine.Cli" />
    <InternalsVisibleTo Include="Shimakaze.Sdk.Engine.Tui" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StbImageSharp" />
    <PackageReference Include="StbImageWriteSharp" />
    <PackageReference Include="System.IO.Hashing" />
    <ProjectReference Include="..\..\csf\Shimakaze.Sdk.Csf.Json\Shimakaze.Sdk.Csf.Json.csproj" />
    <ProjectReference Include="..\..\csf\Shimakaze.Sdk.Csf.Xml\Shimakaze.Sdk.Csf.Xml.csproj" />
    <ProjectReference Include="..\..\csf\Shimakaze.Sdk.Csf.Yaml\Shimakaze.Sdk.Csf.Yaml.csproj" />
    <ProjectReference Include="..\..\csf\Shimakaze.Sdk.Csf\Shimakaze.Sdk.Csf.csproj" />
    <ProjectReference Include="..\..\mix\Shimakaze.Sdk.Mix\Shimakaze.Sdk.Mix.csproj" />
    <ProjectReference Include="..\..\pal\Shimakaze.Sdk.Pal\Shimakaze.Sdk.Pal.csproj" />
    <ProjectReference Include="..\..\shp\Shimakaze.Sdk.Shp\Shimakaze.Sdk.Shp.csproj" />
    <ProjectReference Include="..\..\tmp\Shimakaze.Sdk.Tmp\Shimakaze.Sdk.Tmp.csproj" />
  </ItemGroup>

</Project>