using System.Globalization;

using DotMake.CommandLine;

using ShellProgressBar;

namespace Shimakaze.Sdk.Mix.Toolkit;

[CliCommand(
    Description = "将若干文件打包为一个MIX文件。",
    Parent = typeof(RootCommand))]
internal sealed class PackCommand
{
    [CliOption(Description = "将要被打包的文件列表。", Arity = CliArgumentArity.OneOrMore, AllowMultipleArgumentsPerToken = true)]
    public required List<FileInfo> Input { get; set; }

    [CliArgument(Description = "生成的MIX文件的路径。")]
    public required FileInfo Output { get; set; }

    [CliOption(Description = "文件名对照表位置。留空则不生成文件名对照表")]
    public FileInfo? NameMap { get; set; } = default;

    [CliOption(Description = "使用适用于 Red Alert 或 Tiberian Down 的游戏引擎的ID计算器")]
    public bool IsTD { get; set; }

    [CliOption(Description = "不写入 mix 标记")]
    public bool NoFlag { get; set; }

    [CliOption(Description = "加密 mix (官方河豚加密算法)")]
    public bool Encrypt { get; set; }

    public async Task RunAsync()
    {
        using StreamWriter? nameMapWriter = NameMap?.CreateText();

        using IndeterminateProgressBar progressBar = new("打包中...", new ProgressBarOptions()
        {
            // TODO: 这里需要注意，编码长度 != 字符宽度
            MessageEncodingName = "GB18030",
        });

        if (nameMapWriter is not null)
        {
            nameMapWriter.WriteLine("; Generated By Shimakaze.Sdk.Mix.Toolkit");
            nameMapWriter.WriteLine("");
            nameMapWriter.WriteLine("[NameMap]");
        }
        await using FileStream output = Output.Create();
        IdCalculator idCalculator = IsTD
                ? IdCalculators.TDIdCalculator
                : IdCalculators.TSIdCalculator;
        List<MixEntry> entries = new(Input.Count);
        int offset = 0;
        foreach (var file in Input)
        {
            MixEntry entry = new()
            {
                Id = idCalculator(file.Name),
                Offset = offset,
                Size = (int)file.Length
            };

            nameMapWriter?.WriteLine($"{entry.Id.ToString("X8", CultureInfo.InvariantCulture)} = {file.Name.ToUpperInvariant()}");

            offset += entry.Size;

            entries.Add(entry);
        }
        MixTag? tag = NoFlag
            ? null
            : MixTag.NONE;
        if (Encrypt)
            throw new NotSupportedException("暂时不支持加密 Mix");

        MixMetadata metadata = new((short)Input.Count, offset);
        Mix.WriteMetadata(output, metadata, entries.ToArray(), tag, []);
        int bodyOffset = (int)output.Position;

        for (int i = 0; i < Input.Count; i++)
        {
            MixEntry entry = entries[i];
            FileInfo item = Input[i];

            await using var fs = item.OpenRead();
            await Mix.WriteFileAsync(output, bodyOffset, entry, fs);
        }

        await output.FlushAsync();
    }
}
