<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Include="Diagnostics.csv" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Draco.Lsp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shimakaze.Sdk.Inilyn.Generators\Shimakaze.Sdk.Inilyn.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>