<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <IsInherit>true</IsInherit>
    <NeutralLanguage>zh-Hans</NeutralLanguage>
    <ToolTargetFrameworks>net10.0</ToolTargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shimakaze.Sdk.Engine\Shimakaze.Sdk.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DotMake.CommandLine" />
    <PackageReference Include="XenoAtom.Terminal.UI" />
    <PackageReference Include="XenoAtom.Terminal.UI.Graphics" />
  </ItemGroup>

</Project>
