name: Build

on:
  push:
    branches:
      - master
      - develop
    paths:
      - .github/workflows/build.yml      
      - .config/dotnet-tools.json
      - global.json
      - nuget.config
      - Shimakaze.Sdk.sln
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props
      - "app/**/*"
      - "lib/**/*"
      - "msbuild/**/*"
      - "src/**/*"
      - "test/**/*"
    tags:
      - 'v*'

  pull_request:
    branches:
      - master
      - develop
    paths:
      - .github/workflows/build.yml
      - .config/dotnet-tools.json
      - global.json
      - nuget.config
      - Shimakaze.Sdk.sln
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props
      - "app/**/*"
      - "lib/**/*"
      - "msbuild/**/*"
      - "src/**/*"
      - "test/**/*"
  merge_group:

jobs:
  build-dotnet:
    name: .Net 构建
    runs-on: windows-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v6
        with:
          lfs: true
          fetch-depth: 0

      - name: 配置 .Net 环境
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ./global.json
          cache: false

      - name: 还原本地工具
        run: dotnet tool restore

      - name: 还原
        run: dotnet restore --graph --artifacts-path artifacts

      - name: 生成
        run: dotnet build --graph --artifacts-path artifacts --configuration Release --no-restore

      - name: 打包
        run: dotnet pack --graph --artifacts-path artifacts --configuration Release --no-restore --no-build --include-symbols --include-source

      - name: 生成校验和
        shell: pwsh
        run: |
          $Private:Algorithm = 'SHA256'
          Write-Output "### Build Success :rocket: ">> $env:GITHUB_STEP_SUMMARY
          Write-Output "|FileName|$Private:Algorithm|" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "|:-|:-:|" >> $env:GITHUB_STEP_SUMMARY
          Get-ChildItem artifacts\package\release | ForEach-Object {
            $Private:Name = $PSItem.Name
            $Private:FileHashResult = Get-FileHash $PSItem -Algorithm $Private:Algorithm
            $Private:FileHash = $Private:FileHashResult.Hash
            Write-Output "|$Private:Name|$Private:FileHash|" >> $env:GITHUB_STEP_SUMMARY
          }

      - name: 收集 Nuget 包
        uses: actions/upload-artifact@v7
        with:
          name: nuget-packages
          path: |
            artifacts\package\release\*
          retention-days: 3

  release:
    needs: build-dotnet
    name: 发布
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v6
      - name: Download a Build Artifact
        uses: actions/download-artifact@v8
        with:
          name: nuget-packages
          path: artifact
      - name: 推送 Nuget 包
        shell: pwsh
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: |
          Set-Location artifact
          dotnet nuget push *.nupkg -s nuget -k $env:NUGET_TOKEN --skip-duplicate
          Set-Location ..
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifact/*
