name: Build

on:
  push:
    branches:
      - master
    paths:
      - .editorconfig
      - .github/workflows/build.yml
      - "*.sln"
      - "*.slnx"
      - "**/*.cs"
      - "**/*.csproj"
      - "**/*.props"
      - "**/*.targets"
      - "**/dotnet-tools.json"
      - "**/packages.lock.json"
      - GitVersion.yaml
      - global.json
      - nuget.config
    tags:
      - "v*"

  pull_request:
    branches:
      - master
    paths:
      - .editorconfig
      - .github/workflows/build.yml
      - "*.sln"
      - "*.slnx"
      - "**/*.cs"
      - "**/*.csproj"
      - "**/*.props"
      - "**/*.targets"
      - "**/dotnet-tools.json"
      - "**/packages.lock.json"
      - GitVersion.yaml
      - global.json
      - nuget.config
  merge_group:

jobs:
  build-dotnet:
    name: .Net 构建
    runs-on: windows-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v7
        with:
          lfs: true
          fetch-depth: 0

      - name: 配置 .Net 环境
        uses: actions/setup-dotnet@v6
        with:
          global-json-file: ./global.json

      - name: 初始化 GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: "6.8.x"
          nugetConfigPath: "${{ github.workspace }}/nuget.config"

      - name: 计算版本 Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4

      - name: 生成版本文件
        shell: pwsh
        run: |-
          "<Project>" > Directory.Version.props
          "  <PropertyGroup>" >> Directory.Version.props
          "    <Version>${{ steps.gitversion.outputs.semVer }}</Version>" >> Directory.Version.props
          "    <VersionPrefix>${{ steps.gitversion.outputs.majorMinorPatch }}</VersionPrefix>" >> Directory.Version.props
          "    <VersionSuffix>${{ steps.gitversion.outputs.preReleaseTag }}</VersionSuffix>" >> Directory.Version.props
          "    <PackageVersion>${{ steps.gitversion.outputs.fullSemVer }}</PackageVersion>" >> Directory.Version.props
          "    <InformationalVersion>${{ steps.gitversion.outputs.informationalVersion }}</InformationalVersion>" >> Directory.Version.props
          "    <AssemblyVersion>${{ steps.gitversion.outputs.assemblySemVer }}</AssemblyVersion>" >> Directory.Version.props
          "    <FileVersion>${{ steps.gitversion.outputs.assemblySemFileVer }}</FileVersion>" >> Directory.Version.props
          "    <RepositoryBranch>${{ steps.gitversion.outputs.branchName }}</RepositoryBranch>" >> Directory.Version.props
          "    <RepositoryCommit>${{ steps.gitversion.outputs.sha }}</RepositoryCommit>" >> Directory.Version.props
          "  </PropertyGroup>" >> Directory.Version.props
          "</Project>" >> Directory.Version.props

      - name: 还原
        run: dotnet restore --graph --artifacts-path artifacts

      - name: 生成
        run: dotnet build --graph --artifacts-path artifacts --configuration Release --no-restore

      - name: 打包
        run: dotnet pack --graph --artifacts-path artifacts --configuration Release --no-restore --no-build --include-symbols --include-source

      - name: 生成校验和
        shell: pwsh
        run: |
          $Private:Algorithm = 'SHA256'
          Write-Output "### Build Success :rocket: ">> $env:GITHUB_STEP_SUMMARY
          Write-Output "|FileName|$Private:Algorithm|" >> $env:GITHUB_STEP_SUMMARY
          Write-Output "|:-|:-:|" >> $env:GITHUB_STEP_SUMMARY
          Get-ChildItem artifacts\package\release | ForEach-Object {
            $Private:Name = $PSItem.Name
            $Private:FileHashResult = Get-FileHash $PSItem -Algorithm $Private:Algorithm
            $Private:FileHash = $Private:FileHashResult.Hash
            Write-Output "|$Private:Name|$Private:FileHash|" >> $env:GITHUB_STEP_SUMMARY
          }

      - name: 收集 Nuget 包
        uses: actions/upload-artifact@v7
        with:
          name: nuget-packages
          path: |
            artifacts\package\release\*
          retention-days: 3

  release:
    needs: build-dotnet
    name: 发布
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      discussions: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v7
        with:
          sparse-checkout: "."

      - name: 配置 .Net 环境
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ./global.json
          cache: false

      - name: Download a Build Artifact
        uses: actions/download-artifact@v8
        with:
          name: nuget-packages
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: artifacts/*
          generate_release_notes: true
          prerelease: ${{ contains(github.ref, '-') }}

      # Get a short-lived NuGet API key
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: nuget
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: 推送 Nuget 包
        run: dotnet nuget push artifacts/*.nupkg --api-key "${{ steps.nuget.outputs.NUGET_API_KEY }}" --source "https://www.nuget.org/api/v2/package" --skip-duplicate
