name: Build

on:
  push:
    branches:
      - master
      - feat/**
    pull_request:
      - master

jobs:
  setup:
    name: Setup build environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          global-json-file: ./global.json
  build:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Restore
        run: dotnet restore
      - name: Run Build
        run: dotnet build --configuration Release --no-restore
      - name: Run Test
        run: dotnet test --configuration Release --no-build
  pack:
    needs:
      - setup
      - pack
    runs-on: ubuntu-latest
    steps:
      - name: Create the package
        run: dotnet pack --configuration Release --no-restore --no-build --include-symbols --include-source
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: nuget-packages
          path: src/**/bin/Release/*.*nupkg
          retention-days: 14
