name: Build

on:
  push:
    branches:
      - master
      - develop
      - feat/**
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          lfs: true

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          global-json-file: ./global.json

      - name: Restore
        run: dotnet restore Shimakaze.Sdk.sln

      - name: Build
        run: dotnet build Shimakaze.Sdk.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Shimakaze.Sdk.sln --configuration Release --no-build

      - name: Pack
        run: dotnet pack --configuration Release --no-restore --no-build --include-symbols --include-source

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: nuget-packages-${{ matrix.os }}
          path: src/**/bin/Release/*.*nupkg
          retention-days: 3

      - name: Coveralls Shimakaze.Sdk.Tests
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true
          path-to-lcov: ./test/Shimakaze.Sdk.Tests/coverage.net7.0.info

      - name: Coveralls Shimakaze.Sdk.Build.Tests
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-msbuild-${{ join(matrix.*, '-') }}
          parallel: true
          path-to-lcov: ./test/Shimakaze.Sdk.Build.Tests/coverage.net7.0.info

  finish:
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true
        carryforward: "run-ubuntu-latest,run-windows-latest,run-macos-latest,run-msbuild-ubuntu-latest,run-msbuild-windows-latest,run-msbuild-macos-latest"