<Project>

  <PropertyGroup>
    <NoWarn Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'netstandard2.1'))">$(NoWarn);8604</NoWarn>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Polyfill" PrivateAssets="all" />
    <PackageReference Include="System.ValueTuple"
                      Condition="$(TargetFramework) == 'netstandard2.0' or
                                 $(TargetFramework) == 'netcoreapp2.0' or
                                 $(TargetFramework.StartsWith('net46'))" />
    <PackageReference Include="System.Memory"
                      Condition="$(TargetFrameworkIdentifier) == '.NETStandard' or
                                 $(TargetFrameworkIdentifier) == '.NETFramework' or
                                 $(TargetFramework.StartsWith('netcoreapp2'))" />
    <PackageReference Include="System.Threading.Tasks.Extensions"
                      Condition="$(TargetFramework) == 'netstandard2.0' or
                                 $(TargetFramework) == 'netcoreapp2.0' or
                                 $(TargetFrameworkIdentifier) == '.NETFramework'" />
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation"
                      Condition="$(TargetFrameworkIdentifier) == '.NETFramework'" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>

</Project>