using System.Text;
using System.Text.Json;

using Shimakaze.Sdk.Csf.Json.Converter.V1;

namespace Shimakaze.Sdk.Csf.Json.Tests.Converter.V1;

[TestClass]
public class CsfAdvancedValueJsonConverterTests
{
    private readonly CsfAdvancedValueJsonConverter _converter = new();
    private JsonSerializerOptions? _options;

    // This is the test method for Read method
    [TestMethod]
    public void ReadShouldReturnCorrectCsfValue()
    {
        // Arrange
        ReadOnlySpan<byte> json = """{"value":"Hello","extra":"World"}"""u8;
        Utf8JsonReader reader = new(json);
        reader.Read(); // Move to the start object token

        // Act
        CsfValue result = _converter.Read(ref reader, typeof(CsfValue), _options!);

        // Assert
        Assert.IsNotNull(result);
        Assert.IsInstanceOfType<CsfValue>(result);
        Assert.AreEqual("Hello", result.Value);
        Assert.AreEqual("World", result.ExtraValue);
    }

    // Generated by Sydney This is the test method for Read method
    [TestMethod]
    public void ReadShouldReturnCorrectCsfValue1()
    {
        // Arrange
        ReadOnlySpan<byte> json = """{"value":"Hello","extra":"World"}"""u8;
        Utf8JsonReader reader = new(json);
        reader.Read(); // Move to the start object token

        // Act
        CsfValue result = _converter.Read(ref reader, typeof(CsfValue), _options!);

        // Assert
        Assert.IsNotNull(result);
        Assert.IsInstanceOfType<CsfValue>(result);
        Assert.AreEqual("Hello", result.Value);
    }

    [TestInitialize]
    public void Startup()
    {
        _options ??= new();
        foreach (System.Text.Json.Serialization.JsonConverter item in CsfJsonSerializerOptions.Converters)
        {
            _options.Converters.Add(item);
        }
    }

    // This is the test method for Write method
    [TestMethod]
    public void WriteShouldWriteCorrectJson()
    {
        // Arrange
        CsfValue value = new("Hello", "World");
        using MemoryStream ms = new();
        using Utf8JsonWriter writer = new(ms);

        // Act
        _converter.Write(writer, value, _options!);
        // Flush the writer to get the json bytes
        writer.Flush();
        string json = Encoding.UTF8.GetString(ms.ToArray());

        // Assert
        Assert.AreEqual("""{"value":"Hello","extra":"World"}""", json);
    }
}
