using System.Text;
using System.Text.Json;

using Shimakaze.Sdk.Csf.Json.Converter.V1;

namespace Shimakaze.Sdk.Csf.Json.Tests.Converter.V1;

[TestClass]
public class CsfDataJsonConverterTests
{
    private readonly CsfDataJsonConverter _converter = new();
    private JsonSerializerOptions? _options;

    // This is the test method for Read method
    [TestMethod]
    public void ReadShouldReturnCorrectCsfValue()
    {
        // Arrange
        ReadOnlySpan<byte> json = """{"label":"Hello","values":["The","World"]}"""u8;
        Utf8JsonReader reader = new(json);
        reader.Read(); // Move to the start object token

        // Act
        CsfData result = _converter.Read(ref reader, typeof(CsfData), _options!);

        // Assert
        Assert.IsNotNull(result);
        Assert.IsInstanceOfType<CsfData>(result);
        Assert.AreEqual("Hello", result.LabelName);
        Assert.AreEqual(2, result.Values.Length);
        Assert.AreEqual("The", result.Values[0].Value);
        Assert.AreEqual("World", result.Values[1].Value);
    }

    // Generated by Sydney This is the test method for Read method
    [TestMethod]
    public void ReadShouldReturnCorrectCsfValue1()
    {
        // Arrange
        ReadOnlySpan<byte> json = """{"label":"Hello","value":{"value":"World"},"test":null}"""u8;
        Utf8JsonReader reader = new(json);
        reader.Read(); // Move to the start object token

        // Act
        CsfData result = _converter.Read(ref reader, typeof(CsfData), _options!);

        // Assert
        Assert.IsNotNull(result);
        Assert.IsInstanceOfType<CsfData>(result);
        Assert.AreEqual("Hello", result.LabelName);
        Assert.AreEqual(1, result.Values.Length);
        Assert.AreEqual("World", result.Values[0].Value);
    }

    [TestInitialize]
    public void Startup()
    {
        _options ??= new();
        foreach (System.Text.Json.Serialization.JsonConverter item in CsfJsonSerializerOptions.Converters)
        {
            _options.Converters.Add(item);
        }
    }

    // This is the test method for Write method
    [TestMethod]
    public void WriteShouldWriteCorrectJson()
    {
        // Arrange
        CsfData value = new("Hello", new[]
        {
            new CsfValue("The"),
            new CsfValue("World"),
        });
        using MemoryStream ms = new();
        using Utf8JsonWriter writer = new(ms);

        // Act
        _converter.Write(writer, value, _options!);
        // Flush the writer to get the json bytes
        writer.Flush();
        string json = Encoding.UTF8.GetString(ms.ToArray());

        // Assert
        Assert.AreEqual("""{"label":"Hello","values":["The","World"]}""", json);
    }
}